import type { Metadata } from "next";
import { Bungee } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const bungeeFont = Bungee({
  variable: "--font-bungee",
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Sleep Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` ${bungeeFont.variable} antialiased`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>    
  );
}
